language: rust
# dependencies of kcov, used by coverage
addons:
  apt:
    packages:
      - libcurl4-openssl-dev
      - libelf-dev
      - libdw-dev
      - binutils-dev
      - cmake
    sources:
      - kalakris-cmake
env:
  - PATH=$HOME/.cargo/bin:$PATH
before_script:
  - cargo install cargo-travis -f
script:
  - cargo test --all --features ci
after_success:
  - cargo coveralls
matrix:
  include:
    - rust: stable
    - rust: beta
    - rust: nightly
    # Run rustfmt in its own shard.
    - rust: stable
      env:
        # Give a useful display name in the job list.
        - SHARD=rustfmt
        - PATH=$HOME/.cargo/bin/$PATH
      before_script:
        - rustup toolchain install nightly
        - rustup component add --toolchain stable rustfmt-preview
      script:
        - echo "Checking Gotham codebase with rustfmt release `cargo fmt --version`."
        - cargo fmt --all -- --write-mode=diff

  allow_failures:
    - rust: nightly
