language: rust
sudo: required
dist: trusty
env:
  - PATH=$HOME/.cargo/bin:$PATH
script:
  - cargo test -j2 --all
matrix:
  fast_finish: true
  include:
    - rust: stable
    - rust: beta
    - rust: nightly
    # Run rustfmt in its own shard.
    - rust: stable
      env:
        # Give a useful display name in the job list.
        - SHARD=rustfmt
        - PATH=$HOME/.cargo/bin/:$PATH
      before_script:
        - rustup component add --toolchain stable rustfmt-preview
      script:
        - echo "Checking Gotham codebase with rustfmt release `cargo fmt --version`."
        - cargo fmt --all -- --check
    # Run Clippy in its own shard.
    - rust: stable
      env:
        - SHARD=clippy
        - PATH=$HOME/.cargo/bin/:$PATH
      before_script:
        - rustup component add --toolchain stable clippy
      script:
        - echo "Checking Gotham codebase with Clippy release `cargo clippy --version`."
        - cargo clippy --all --profile test
  allow_failures:
    - rust: nightly
addons:
  apt:
    packages:
        - libssl-dev
after_success: |
  if [[ "$TRAVIS_RUST_VERSION" == stable && "$SHARD" != rustfmt ]]; then
    bash <(curl https://raw.githubusercontent.com/xd009642/tarpaulin/master/travis-install.sh)
    cargo tarpaulin --all --forward --out Xml
    bash <(curl -s https://codecov.io/bash)
  fi
