[package]
name = "gotham_examples_path_regex"
description = "Shows how to match against Regex patterns in path segments."
version = "0.0.0"
publish = false
edition = "2018"

[dependencies]
gotham = { path = "../../../gotham" }
gotham_derive = { path = "../../../gotham_derive" }
serde = "1"
serde_derive = "1"
