[package]
name = "gotham_examples_path_regex"
description = "Shows how to match against Regex patterns in path segments."
version = "0.0.0"
publish = false

[dependencies]
gotham = { path = "../../../gotham" }
gotham_derive = { path = "../../../gotham_derive" }

hyper = { version = "0.13.0-alpha.4", features = ["unstable-stream"] }
mime = "0.3"
serde = "1"
serde_derive = "1"
