[package]
name = "gotham_examples_hello_world"
description = "A Hello World example application for working with Gotham."
version = "0.0.0"
publish = false

[dependencies]
gotham = { path = "../../gotham" }

hyper = "0.12"
mime = "0.3"
reqwest = "0.9.19"
