[package]
name = "gotham_examples_hello_world"
description = "A Hello World example application for working with Gotham."
version = "0.0.0"
publish = false

[dependencies]
gotham = { path = "../../gotham" }

hyper = "0.13.1"
mime = "0.3"
