[package]
name = "gotham_examples_headers_setting"
description = "Setting a header value for a Gotham web framework response"
version = "0.0.0"
authors = ["Eren GÃ¼ven <erenguven0@gmail.com>"]
publish = false
edition = "2018"

[dependencies]
gotham = { path = "../../../gotham" }
