[package]
name = "gotham_derive"
version = "0.2.0-dev"
authors = ["Bradley Beddoes <bradleybeddoes@gmail.com>",
           "Shaun Mangelsdorf <s.mangelsdorf@gmail.com>"]
description = "Macros 1.1 implementations for Gotham traits"
license = "MIT/Apache-2.0"
repository = "https://github.com/gotham-rs/gotham"
readme = "README.md"
categories = ["web-programming::http-server"]
keywords = ["http", "async", "web", "framework", "gotham"]

[dependencies]
syn = "0.11.11"
quote = "0.3.15"

[lib]
proc-macro = true
