[package]
name = "gotham_examples_middleware_multiple_pipelines"
description = "Provides examples of using multiple middleware pipelines for different routes."
version = "0.0.0"
publish = false
edition = "2018"

[dependencies]
gotham = { path = "../../../gotham" }
gotham_derive = { path = "../../../gotham_derive" }
futures = "0.3.1"
serde = "1.0"
serde_derive = "1.0"
