[package]
name = "gotham_examples_path_introduction"
description = "An introduction to extracting request path segments, in a type safe way, with the Gotham web framework"
version = "0.0.0"
authors = ["Nicolas Pochet <npochet@gmail.com>"]
publish = false
edition = "2018"

[dependencies]
gotham = { path = "../../../gotham" }
serde = { version = "1.0", features = ["derive"] }
