[package]
name = "gotham_examples_middleware_introduction"
description = "Introduces the Middleware and Pipeline concepts provided by the Gotham web framework"
version = "0.0.0"
publish = false
edition = "2018"

[dependencies]
gotham = { path = "../../../gotham" }
gotham_derive = { path = "../../../gotham_derive" }
futures = "0.3.1"
