[package]
name = "gotham_examples_templating_tera"
description = "A Tera template engine usage example application for Gotham."
version = "0.0.0"
publish = false
edition = "2018"

[dependencies]
gotham = { path = "../../../gotham" }

mime = "0.3"
tera = "1.5"
lazy_static = "1.0"
