[package]
name = "gotham_examples_path_globs"
description = "Shows how to match arbitrarily many path segments."
version = "0.0.0"
authors = ["Daniel Wagner-Hall <dawagner@gmail.com>"]
publish = false
edition = "2018"

[dependencies]
gotham = { path = "../../../gotham" }
gotham_derive = { path = "../../../gotham_derive" }

mime = "0.3"
serde = { version = "1.0", features = ["derive"] }