[package]
name = "gotham_examples_shared_state"
description = "An introduction to shared state across Gotham handlers"
version = "0.0.0"
publish = false

[dependencies]
gotham = { path = "../../gotham" }
gotham_derive = { path = "../../gotham_derive" }

hyper = "0.13.1"
mime = "0.3"
