[package]
name = "gotham_examples_routing_scopes"
description = "An example of the Gotham web framework `Router` that shows how to combine `Routes` under a common root using scopes."
version = "0.0.0"
publish = false

[dependencies]
gotham = { path = "../../../gotham" }
gotham_derive = { path = "../../../gotham_derive" }

hyper = "0.11"
futures = "~0.1.11"
mime = "0.3"
