[package]
name = "gotham_examples_hello_world_tls"
description = "A Hello World example application for working with Gotham and TLS."
version = "0.0.0"
publish = false
edition = "2018"

[dependencies]
gotham = { path = "../../gotham", features = ["rustls"] }
rustls-pemfile = "2.0"
