[package]
name = "gotham_examples_custom_service"
description = "Using Gotham in a pre-existing Hyper service"
version = "0.0.0"
publish = false
edition = "2018"

[dependencies]
anyhow = "1.0"
futures = "0.3"
gotham = { path = "../../gotham" }
http = "0.2"
hyper = { version = "0.14.4", features = ["full"] }
tokio = { version = "1.3.0", features = ["full"] }
