[package]
name = "gotham_examples_into_response_introduction"
description = "An introduction to using the Gotham web framework's `IntoResponse` trait."
version = "0.0.0"
authors = ["Nicolas Pochet <npochet@gmail.com>"]
publish = false
edition = "2018"

[dependencies]
gotham = { path = "../../../gotham" }
gotham_derive = { path = "../../../gotham_derive" }
serde = "1"
serde_derive = "1"
serde_json = "1"
