[package]
name = "gotham_examples_into_response_introduction"
description = "An introduction to using the Gotham web framework's `IntoResponse` trait."
version = "0.0.0"
authors = ["Nicolas Pochet <npochet@gmail.com>"]
publish = false
edition = "2018"

[dependencies]
gotham = { path = "../../../gotham" }
gotham_derive = { path = "../../../gotham_derive" }

mime = "0.3"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1"
