[package]
name = "gotham_examples_routing_http_verbs"
description = "An example of the Gotham web framework Router that shows how to route requests to handlers based on HTTP verbs."
version = "0.0.0"
publish = false

[dependencies]
gotham = { path = "../../../gotham" }
gotham_derive = { path = "../../../gotham_derive" }

hyper = "0.13.1"
mime = "0.3"
