[package]
name = "gotham_examples_query_string_introduction"
description = "An introduction to extracting query string name/value pairs, in a type safe way, with the Gotham web framework"
version = "0.0.0"
authors = ["Nicolas Pochet <npochet@gmail.com>"]
publish = false
edition = "2018"

[dependencies]
gotham = { path = "../../../gotham" }
gotham_derive = { path = "../../../gotham_derive" }

mime = "0.3"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1"
